config/routes.rb
Rails.application.routes.draw do
  resources :mail_lists
  resources :transportations
  resources :usefuls
  resources :ocean_inspects
  resources :staffs
  resources :boats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:  'ocean_inspects#index'
  resources :weathers
  resources :managements
  get 'ocean_inspects/:id/logbooks', to: 'ocean_inspects#logbooks', as: 'logbooks'
  get 'cwb', to: 'weathers#cwb', as: 'cwb'
  get 'record', to: 'ocean_inspects#record', as: 'record'
  get 'transportations/:id/sendmail', to: 'transportations#mailer', as: 'email'
end

app/models/transportation.rb
class Transportation < ApplicationRecord
  has_many :transportationcrews, dependent: :destroy, inverse_of: :transportation

  accepts_nested_attributes_for :transportationcrews, reject_if: :all_blank, allow_destroy: true

  before_save do
    @date = self.date
    self.year = @date.split("-")[0].to_i-1911
    self.month = @date.split("-")[1]
    self.day = @date.split("-")[2]
  end

  after_initialize :set_defaults, unless: :persisted?
  # The set_defaults will only work if the object is new

  def set_defaults
    self.note  ||= '搭乘內太空號運補船'
    self.concat ||= "(06) 999-1112"
  end

end

app/controllers/transportations_controller.rb
class TransportationsController < ApplicationController
  before_action :set_transportation, only: [:show, :edit, :update, :destroy, :mailer]

  # GET /transportations
  # GET /transportations.json
  def index
    @transportations = Transportation.all
  end

  def mailer
    SendMailMailer.transportation(@transportation).deliver_later!
    redirect_to transportations_path, notice: '信件已發送'
  end
  # GET /transportations/1
  # GET /transportations/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = TransportationPdf.new(@transportation)
        send_data pdf.render, filename: "海洋國家公園#{@transportation.date}運補船人員名冊.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  # GET /transportations/new
  def new
    @transportation = Transportation.new
    1.times {@transportation.transportationcrews.build}
  end

  # GET /transportations/1/edit
  def edit
  end

  # POST /transportations
  # POST /transportations.json
  def create
    @transportation = Transportation.new(transportation_params)

    respond_to do |format|
      if @transportation.save
        format.html { redirect_to @transportation, notice: '運補名冊已新建完成' }
        format.json { render :show, status: :created, location: @transportation }
      else
        format.html { render :new }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transportations/1
  # PATCH/PUT /transportations/1.json
  def update
    respond_to do |format|
      if @transportation.update(transportation_params)
        format.html { redirect_to @transportation, notice: '運補名冊已更新完成' }
        format.json { render :show, status: :ok, location: @transportation }
      else
        format.html { render :edit }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transportations/1
  # DELETE /transportations/1.json
  def destroy
    @transportation.destroy
    respond_to do |format|
      format.html { redirect_to transportations_url, notice: '本項運補名冊已刪除' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transportation
      @transportation = Transportation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transportation_params
      params.require(:transportation).permit(:date, :year, :month, :day, :status, :direction, :note, :staff_id, transportationcrews_attributes: [:id, :staff_id, :direction, :status, :_destroy])
    end
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/views/transportations/_form.html.erb
<%= simple_form_for @transportation do |f| %>
  <div class="col-xs-12">
    <%= f.input :date, label: '運補日期',wrapper_html:{ class: ''} %>
    <hr>
    <div class="form-inputs">
      <div id='add_crews'>
        <p>人員名冊</p>
        <%= f.simple_fields_for :transportationcrews do |crew| %>
          <%= render 'transportationcrew_fields', f:  crew %>
        <% end %>
        <hr>
        <div class='links'>
          <%= link_to_add_association '新增人員', f, :transportationcrews , {class: 'btn btn-sm btn-success', type: "button" } %>
        </div>
        <hr>
      </div>
      <%= f.input :note, label: '備註' %>
      <%= f.input :concat, label: '聯絡電話' %>
    </div>
    <br>
    <hr>
    <div class="form-actions">
      <%= link_to "取消" ,transportations_path(@transportation),  class: "btn btn-outline-danger pull-xs-left"%>
      <%= f.button :submit,  "新建｜更新名冊", class: "btn btn-outline-primary pull-xs-right" , data: { disable_with: "新建中..." }%>
    </div>
  </div>
<% end %>

<script>
  // The date picker (read the docs)
  $('#transportation_date').pickadate({format: 'yyyy-mm-dd', formatSubmit: false})
</script>

app/views/transportations/_transportationcrew_fields.html.erb
<div class='nested-fields col-xs-12 p-x-0'>
  <%= f.input :staff_id, label: '姓名',collection: Staff.all, input_html: { class: "custom-select" }, wrapper_html:{ class: 'col-xs-3 p-l-0'}%>
  <%= f.input :status, label: '上/下',collection: ["上島", "下島"],input_html: { class: "custom-select" },  wrapper_html:{ class: 'col-xs-2 p-l-0'}%>
  <%= f.input :direction, label: '運補地點',collection: ["馬公至東吉嶼","馬公至東嶼坪","東吉嶼至馬公","東嶼坪至馬公"],input_html: { class: "custom-select" },  wrapper_html:{ class: 'col-xs-6 p-l-0'} %>
  <div class="col-xs-1 p-x-0">
    <br>
    <br>
    <%= link_to_remove_association "移除", f, {class: 'btn btn-sm btn-danger p-y-20', type: "button" } %>
  </div>

</div>

app/views/transportations/edit.html.erb
<div class="form-inputs col-sm-10 offset-sm-1 col-xl-6 offset-xl-3 p-x-0">
  <p></p>
  <h2 class="Display-4 text-center p-x-1">編輯運補人員名冊</h2>
  <hr>

  <%= render 'form', transportation: @transportation %>

</div>

app/views/transportations/index.html.erb
<div class="page-header">
  <p></p>
  <h2 class="h3">馬公運補名冊  <%= link_to "寄信名單", mail_lists_path, class: "btn btn-outline-success pull-xs-right " %><%= link_to "新增", new_transportation_path, class: "btn btn-outline-primary pull-xs-right " %></h2>
  <hr>
</div>
<table class="table table-hover table-sm">
  <thead class="bg-primary">
    <tr>
      <th>運補日期</th>
      <th>運補人員</th>
      <th>功能</th>
    </tr>
  </thead>
  <tbody>
    <%  @transportations.each do |tp| %>
      <tr>
        <td><%= link_to tp.month.to_s + ' 月 '  + tp.day.to_s + '日', transportation_path(tp) %></td>
        <% @crews = String.new  %>
        <% tp.transportationcrews.each do |crew| %>
          <% @crews += "#{Staff.find(crew.staff_id).name}、" %>
        <% end %>
        <% @crews[-1] = "" %>
        <td><%= @crews %></td>
        <td class="btn-group" role="group">
            <%= link_to("編輯", edit_transportation_path(tp), class: "btn btn-sm btn-outline-primary")%>
            <%= link_to("刪除", transportation_path(tp),    class: "btn btn-sm btn-outline-primary",
                        method: :delete, data: { confirm: "確定刪除該筆紀錄?" } )%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>

app/views/transportations/new.html.erb
<div class="form-inputs col-sm-10 offset-sm-1 col-xl-6 offset-xl-3 p-x-0">
  <p></p>
  <h2 class="Display-4 text-center p-x-1">新增人員運補名冊</h2>
  <hr>

  <%= render 'form', transportation: @transportation %>

</div>

app/views/transportations/show.html.erb
<div class="col-sm-10 offset-sm-1 col-xl-8 offset-xl-2 p-x-0">
  <p></p>
  <h2 class="Display-4 text-center p-x-1"><%= "#{@transportation.year}年#{@transportation.month}月#{@transportation.day}日 - 運補人員名冊" %></h2>
  <hr>
  <table class="table table-hover table-sm">
    <thead class="bg-primary">
      <tr>
        <th>單位</th>
        <th>職稱</th>
        <th>姓名</th>
        <th>身份證字號</th>
        <th>狀態</th>
        <th>運補地點</th>
      </tr>
    </thead>
    <% @crews = @transportation.transportationcrews %>
    <tbody>
      <%  @crews.each do |crew| %>
        <tr>
          <td><%= Staff.find(crew.staff_id).role %></td>
          <td><%= Staff.find(crew.staff_id).title %></td>
          <td><%= Staff.find(crew.staff_id).name %></td>
          <td><%= Staff.find(crew.staff_id).id_number %></td>
          <td><%= crew.status %></td>
          <td><%= crew.direction %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <p class="text-xs-center">
    <%= "共計上島#{@crews.where(status: "上島").count}人、下島#{@crews.where(status: "下島").count}人" %>
  </p>
  <p class="text-xs-center">
    <%= "備註： #{@transportation.note}\t|\t聯絡電話： #{@transportation.concat}" %>
  </p>
  <hr>
  <div id="controll" class="col-lg-12 p-a-0 btn-group" role="group">
    <div class="col-md-3">
      <%= link_to("回運補清單",transportations_path, class: "btn btn-outline-success") %>
    </div>
    <div class="text-xs-right col-md-9" >
      <%= link_to("編輯紀錄表", edit_transportation_path(@transportation), class: "btn btn-outline-danger") %>
      <!-- 多選button 輸出各種不同表單 -->
      <div class="btn-group  dropup">
        <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          輸出PDF表單
        </button>
        <div class="dropdown-menu">
          <%= link_to "預覽", transportation_path(params[:id],format: "pdf"), target: '_blank',class: "dropdown-item" %>
          <%= link_to '送信', email_path(params[:id]), class: "dropdown-item" %>
        </div>
      </div>

    </div>
  </div>
</div>