config/routes.rb
Rails.application.routes.draw do
  resources :mail_lists
  resources :transportations
  resources :usefuls
  resources :ocean_inspects
  resources :staffs
  resources :boats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:  'ocean_inspects#index'
  resources :weathers
  resources :managements
  get 'ocean_inspects/:id/logbooks', to: 'ocean_inspects#logbooks', as: 'logbooks'
  get 'cwb', to: 'weathers#cwb', as: 'cwb'
  get 'record', to: 'ocean_inspects#record', as: 'record'
  get 'transportations/:id/sendmail', to: 'transportations#mailer', as: 'email'
end

app/models/ocean_inspect.rb
class OceanInspect < ApplicationRecord
  has_many :diaries, dependent: :destroy, inverse_of: :ocean_inspect
  accepts_nested_attributes_for :diaries, reject_if: :all_blank, allow_destroy: true

  before_save do
    wday_i = self.date.to_date.wday.to_i
    @wday = "日" if wday_i === 0
    @wday = "一" if wday_i === 1
    @wday = "二" if wday_i === 2
    @wday = "三" if wday_i === 3
    @wday = "四" if wday_i === 4
    @wday = "五" if wday_i === 5
    @wday = "六" if wday_i === 6
    self.wday = @wday

    self.gas_consumption = self.distance.to_f * Boat.find(self.boat_id).fuelConsumption.to_f

    if attribute_present?("crew")
      self.crew.gsub!(/[\[\]\"]/, "")
      self.crew[0] = ""
      self.crew.gsub!(/,/, " 、")
    end
    if attribute_present?("location")
      self.location.gsub!(/[\[\]\"]/, "")
      self.location[0] = ""
      self.location.gsub!(/,/, " 、")
    end
    if attribute_present?("work_items")
      self.work_items.gsub!(/[\[\]\"]/, "")
      self.work_items[0] = ""
      self.work_items.gsub!(/,/, " 、")
    end
    @date = self.date
    self.year = @date.split("-")[0].to_i-1911
    self.month = @date.split("-")[1]
    self.day = @date.split("-")[2]

  end


  mount_uploader :pics, ImageUploader
  mount_uploader :map, ImageUploader

  # Validation
  validates :date, presence: true
  validates :s_time, presence: true
  validates :e_time, presence: true
  validates :boat_id, presence: true
  validates :captain, presence: true
  validates :distance, presence: true
  validates :leader, presence: true
end

app/controllers/ocean_inspects_controller.rb
class OceanInspectsController < ApplicationController
  before_action :set_ocean_inspect, only: [:show, :edit, :update, :destroy, :logbooks]



  def record
    year = Time.now.year - 1911
    month = Time.now.month
    data = params[:date].to_s.split("-")
    year = data[0].to_i - 1911 if data != []
    month = data[1] if data != []
    @insps = OceanInspect.where(year: year).where(month: month)
    if @insps.length != 0
      respond_to do |format|
        format.xlsx  {
          response.headers['Content-Disposition'] = "attachment; filename=\"#{@insps.first.year}年#{@insps.first.month}月巡護小艇使用紀錄表.xlsx\""
        }
      end
    else
      redirect_to root_path
    end
  end

  # GET /ocean_inspects
  # GET /ocean_inspects.json
  def index
    year = Time.now.year - 1911
    month = Time.now.month
    data = params[:date].to_s.split("-")
    year = data[0].to_i - 1911 if data != []
    month = data[1] if data != []

    @ocean_inspects = OceanInspect.where(year: year).where(month: month).order(:date)
  end

  # GET /ocean_inspects/1
  # GET /ocean_inspects/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OceanInspectPdf.new(@ocean_inspect)
        send_data pdf.render, filename: "澎湖南方四島海洋巡護紀錄表#{@ocean_inspect.year+@ocean_inspect.month+@ocean_inspect.day}.pdf",
                              type: "application/pdf",
                              disposition: "inline"


      end
    end
  end

  def logbooks
    respond_to do |format|
      format.pdf do
        logbooks = LogbooksPdf.new(@ocean_inspect)
        send_data logbooks.render, filename: "#{@ocean_inspect.year+@ocean_inspect.month+@ocean_inspect.day}航行日誌.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  # GET /ocean_inspects/new
  def new
    @ocean_inspect = OceanInspect.new
  end

  # GET /ocean_inspects/1/edit
  def edit
  end

  # POST /ocean_inspects
  # POST /ocean_inspects.json
  def create
    @ocean_inspect = OceanInspect.new(ocean_inspect_params)

    respond_to do |format|
      if @ocean_inspect.save
        format.html { redirect_to @ocean_inspect, notice: '海域巡查紀錄新建完成～' }
        format.json { render :show, status: :created, location: @ocean_inspect }
      else
        format.html { render :new }
        format.json { render json: @ocean_inspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ocean_inspects/1
  # PATCH/PUT /ocean_inspects/1.json
  def update
    respond_to do |format|
      if @ocean_inspect.update(ocean_inspect_params)
        format.html { redirect_to @ocean_inspect, notice: '海域巡查紀錄更新完成～' }
        format.json { render :show, status: :ok, location: @ocean_inspect }
      else
        format.html { render :edit }
        format.json { render json: @ocean_inspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ocean_inspects/1
  # DELETE /ocean_inspects/1.json
  def destroy
    @ocean_inspect.destroy
    respond_to do |format|
      format.html { redirect_to ocean_inspects_url, notice: '已刪除該筆海域巡查紀錄' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ocean_inspect
      @ocean_inspect = OceanInspect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ocean_inspect_params
      params.require(:ocean_inspect).permit( :pics, :map, :pics_cache, :map_cache, :remove_pics, :s_time, :e_time, :boat_id, :weather, :wave, :leader, :location , :crew, :gas, :oil, :distance, :captain, :diary, :work_items, :note, :year, :month, :day, :date,crew: [], location: [], work_items: [], diaries_attributes: [:id, :item, :ocean_inspect_id, :_destroy])
    end
end

app/helpers/ocean_inspects_helper.rb
module OceanInspectsHelper
end

app/views/ocean_inspects/_diary_fields.html.erb
<div class="crearfix">
  <div class='nested-fields'>
      <%= f.input :item, label:'項目' %>
      <%= link_to_remove_association "移除此項", f , type: "button", class: "btn btn-sm btn-danger"%>

  </div>
</div>

app/views/ocean_inspects/edit.html.erb
<p></p>
<h2 class="Display-4 text-center p-x-1">編輯海域巡查紀錄</h2>
<hr>
<%= simple_form_for(@ocean_inspect) do |f| %>
  <% if f.error_notification != nil %>
    <%= f.error_notification %>
  <% end %>
  <div class="form-inputs col-xl-12 p-x-0">
    <div class="col-xl-5 p-x-0">
      <div id="time" class="col-xl-12 p-x-0">
        <%= f.input :date, label: '巡查日期',wrapper_html:{ class: 'col-xl-6 col-lg-3'} %>
        <%= f.input :s_time, label: '出航時間' , wrapper_html:{ class: 'col-xl-3 col-lg-2'} %>
        <%= f.input :e_time, label: '返航時間' , wrapper_html:{ class: 'col-xl-3 col-lg-2'}%>
      </div>
      <div id="boat" class="col-xl-12 p-x-0">
        <%= f.input :boat_id, collection: Boat.all, label: '使用船隻', input_html: { class: "custom-select"} ,wrapper_html:{ class: 'col-xl-6 col-lg-3'}%>
        <%= f.input :captain, collection: Staff.where("role ='船公司'"), label: '船長', input_html: { class: "custom-select" }, wrapper_html:{ class: 'col-xl-6 col-lg-2'}%>
        <%= f.input :distance, label: '航行海浬' ,wrapper_html:{ class: 'col-xl-3 col-lg-3'}%>
        <%= f.input :gas_consumption ,label: '汽油消耗(L)',wrapper_html:{ class: 'col-xl-3 col-lg-3'} %>
        <%= f.input :gas ,label: '添加汽油(L)',wrapper_html:{ class: 'col-xl-3 col-lg-3'} %>
        <%= f.input :oil, label: '添加機油(L)', wrapper_html:{ class: 'col-xl-3 col-lg-3'} %>
      </div>
      <div id="work" class="col-xl-12 p-x-0">
        <%= f.input :leader, collection: Staff.where("role ='海洋國家公園'"), label: '領隊', input_html: { class: "custom-select" }, wrapper_html:{ class: 'col-xl-4 col-lg-2'}%>
        <%= f.input :crew, label: '搭載人員 <span class="small"> <不含領隊></span>'.html_safe, wrapper_html:{ class: 'col-xl-8 col-lg-6'}%>
        <%= f.input :location, label: '巡查海域',wrapper_html:{ class: 'col-xl-12 col-lg-4'} %>
        <%= f.input :work_items, label: '工作項目', wrapper_html:{ class: 'col-xl-12 col-lg-12'} %>
      </div>
    </div>
    <div class="col-xl-7 col-lg-12">
      <div id='diaries' class="form-group row p-x-2">
        <p>巡查記事</p>
        <%= f.simple_fields_for :diaries do |diary| %>
          <%= render 'diary_fields', f: diary %>
        <% end %>
        <div class='links p-y-1'>
          <%= link_to_add_association '新增項目', f, :diaries, type: "button", class: "btn btn-sm btn-primary"%>
        </div>
        <hr>
      </div>
      <div id="pic">
        <%= f.input :map, label:'巡查地圖'.html_safe ,label_html: { class: "custom-file"} do %>
          <%= image_tag @ocean_inspect.map, class: "img-thumbnail",style: "width: 150px; height: 150px" if @ocean_inspect.map? %>
          <%= f.file_field :map ,class: "form-control-file btn-sm"%>
          <%= f.hidden_field :map_cache %>
        <% end %>
      </div>
      <hr>
      <div id="pic">
        <%= f.input :pics, label:'巡查照片'.html_safe ,label_html: { class: "custom-file"} do %>
          <%= image_tag @ocean_inspect.pics, class: "img-thumbnail",style: "width: 150px; height: 150px" if @ocean_inspect.pics? %>
          <%= f.file_field :pics, class: "form-control-file btn-sm"%>
          <%= f.hidden_field :pics_cache %>
        <% end %>
      </div>
      <div class="">
        <%= f.input :note ,label: '備註事項', placeholder: "避颱..."%>
      </div>
    </div>
  </div>
  <div class="form-actions col-xs-12">
    <hr>
    <%= f.button :submit,  "修訂表單", class: "btn btn-primary pull-xs-right" , data: { disable_with: "修訂中..." }%>
  </div>
<% end %>




<script>
  // The date picker (read the docs)
  $('#ocean_inspect_date').pickadate({format: 'yyyy-mm-dd',max: true,
formatSubmit: false})
  $('#ocean_inspect_s_time').pickatime({format: 'HH:i',formatSubmit: false})
  $('#ocean_inspect_e_time').pickatime({format: 'HH:i',formatSubmit: false})

</script>

app/views/ocean_inspects/index.html.erb
<div class="page-header">
  <p></p>
  <h2 class="h3">海域巡查紀錄表  <%= link_to("新的海域巡查", new_ocean_inspect_path, class: "btn btn-outline-primary pull-xs-right ") %></h2>
  <hr>
</div>
<table class="table table-hover table-sm">
  <thead class="bg-primary">
    <tr>
      <th>巡查日期</th>
      <th>巡查時間</th>
      <th>領隊</th>
      <th class="hidden-lg-down">工作項目</th>
      <th class="hidden-md-down">航行浬程</th>
      <th class="hidden-md-down">天氣</th>
      <th class="hidden-md-down">浪高(米)</th>
      <th class="hidden-xs-down">船長</th>
      <th class="hidden-xs-down">使用船艇</th>
      <th class="hidden-sm-down">加油(升)</th>
      <th>功能</th>
    </tr>
  </thead>
  <tbody>
    <% @ocean_inspects.each do |insp| %>
      <% id = insp.year + insp.month + insp.day %>
      <tr>
        <td><%= link_to insp.month.to_s + ' / '  +insp.day.to_s, ocean_inspect_path(insp) %></td>
        <td><%= insp.s_time + ' - ' + insp.e_time %></td>
        <td><%= Staff.find(insp.leader).name %></td>
        <td class="hidden-lg-down"><%= insp.work_items %></td>
        <td class="hidden-md-down"><%= insp.distance %></td>
        <td class="hidden-md-down"><%= WeatherMonthly.find(id).weather %></td>
        <td class="hidden-md-down"><%= WeatherMonthly.find(id).wave %></td>
        <td class="hidden-xs-down"><%= Staff.find(insp.captain).name %></td>
        <td class="hidden-xs-down"><%= Boat.find(insp.boat_id).name %></td>
        <td class="hidden-sm-down"><%= insp.gas %></td>
        <td class="btn-group" role="group">
            <%= link_to("編輯", edit_ocean_inspect_path(insp), class: "btn btn-sm btn-outline-primary")%>
            <%= link_to("刪除", ocean_inspect_path(insp),    class: "btn btn-sm btn-outline-primary",
                        method: :delete, data: { confirm: "確定刪除該筆紀錄?" } )%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<div class="col-xs-12 col-md-4 col-lg-3 p-x-0">
  <form action="/" accept-charset="UTF-8" method="get">
    <div class="input-group">
      <input name="date" id="pickmonth" type="text" class="form-control" placeholder="選擇年/月...">
      <span class="input-group-btn">
        <button  name="commit" class="btn btn-success" type="submit">檢視月報</button>
      </span>
    </div>
  </form>
</div>
<div class="col-xs-12 col-md-4 col-lg-3 p-x-0">
  <form action="/record" accept-charset="UTF-8" method="get">
    <div class="input-group">
      <input name="date" id="pickmonth2" type="text" class="form-control" placeholder="選擇年/月...">
      <input name="format" value="xlsx" type="hidden">
      <span class="input-group-btn">
        <button  name="commit" class="btn btn-danger" type="submit">輸出月報</button>
      </span>
    </div>
  </form>
</div>

<script>
  // The date picker (read the docs)
  $('#pickmonth').pickadate({format: 'yyyy-mm',max: true})
  $('#pickmonth2').pickadate({format: 'yyyy-mm',max: true})
</script>

app/views/ocean_inspects/new.html.erb
<p></p>
<h2 class="Display-4 text-center p-x-1">新增海域巡查紀錄</h2>
<hr>
<%= simple_form_for(@ocean_inspect) do |f| %>
  <% if f.error_notification != nil %>
    <%= f.error_notification %>
  <% end %>
  <div class="form-inputs col-xl-12 p-x-0">
    <div class="col-xl-5 p-x-0">
      <div id="time" class="col-xl-12 p-x-0">
        <%= f.input :date, label: '巡查日期',wrapper_html:{ class: 'col-xl-6 col-lg-3'} %>
        <%= f.input :s_time, label: '出航時間' , wrapper_html:{ class: 'col-xl-3 col-lg-2'} %>
        <%= f.input :e_time, label: '返航時間' , wrapper_html:{ class: 'col-xl-3 col-lg-2'}%>
      </div>
      <div id="boat" class="col-xl-12 p-x-0">
        <%= f.input :boat_id, collection: Boat.all, label: '使用船隻', input_html: { class: "custom-select"} ,wrapper_html:{ class: 'col-xl-6 col-lg-3'}%>
        <%= f.input :captain, collection: Staff.where("role ='船公司'"), label: '船長', input_html: { class: "custom-select" }, wrapper_html:{ class: 'col-xl-6 col-lg-2'}%>
        <%= f.input :distance, label: '航行海浬' ,wrapper_html:{ class: 'col-xl-4 col-lg-3'}%>
        <%= f.input :gas ,label: '添加汽油(L)',wrapper_html:{ class: 'col-xl-4 col-lg-3'} %>
        <%= f.input :oil, label: '添加機油(L)', wrapper_html:{ class: 'col-xl-4 col-lg-3'} %>
      </div>
      <div id="work" class="col-xl-12 p-x-0">
        <%= f.input :leader, collection: Staff.where("role ='海洋國家公園'"), label: '領隊', input_html: { class: "custom-select" }, wrapper_html:{ class: 'col-xl-4 col-lg-3'}%>
        <%= f.input :crew, as: :check_boxes, collection: Staff.all, label: '搭載人員 <span class="small">  <不含領隊></span>'.html_safe, value_method: :name, label_html: { class: "form-check" },wrapper_html:{ class: 'col-xl-8 col-lg-4'}%>
        <%= f.input :location, as: :check_boxes, collection: Useful.where("catalog ='巡查海域'"), value_method: :name, label: '巡查海域',label_html: { class: "form-check" },wrapper_html:{ class: 'col-xl-12 col-lg-4'} %>
        <%= f.input :work_items, as: :check_boxes, collection: Useful.where("catalog ='工作項目'"), label: '工作項目',value_method: :name, label_html: { class: "form-check" } ,wrapper_html:{ class: 'col-xl-12 col-lg-4'} %>
      </div>
    </div>
    <div class="col-xl-7 col-lg-12">
      <div id='diaries' class="form-group row p-x-2">
        <p>巡查記事</p>
        <%= f.simple_fields_for :diaries do |diary| %>
          <%= render 'diary_fields', f: diary %>
        <% end %>
        <div class='links p-y-1'>
          <%= link_to_add_association '新增項目', f, :diaries, type: "button", class: "btn btn-sm btn-primary"%>
        </div>
        <hr>
      </div>
      <div id="pic">
        <%= f.input :map, label:'巡查地圖'.html_safe ,label_html: { class: "custom-file"} do %>
          <%= image_tag @ocean_inspect.map, class: "img-thumbnail",style: "width: 150px; height: 150px" if @ocean_inspect.map? %>
          <%= f.file_field :map ,class: "form-control-file btn-sm"%>
          <%= f.hidden_field :map_cache %>
        <% end %>
      </div>
      <hr>
      <div id="pic">
        <%= f.input :pics, label:'巡查照片'.html_safe ,label_html: { class: "custom-file"} do %>
          <%= image_tag @ocean_inspect.pics, class: "img-thumbnail",style: "width: 150px; height: 150px" if @ocean_inspect.pics? %>
          <%= f.file_field :pics, class: "form-control-file btn-sm"%>
          <%= f.hidden_field :pics_cache %>
        <% end %>
      </div>
      <div class="">
        <%= f.input :note ,label: '備註事項', placeholder: "避颱..."%>
      </div>
    </div>
  </div>
  <div class="form-actions col-xs-12">
    <hr>
    <%= f.button :submit,  "新建海域巡查紀錄", class: "btn btn-primary pull-xs-right" , data: { disable_with: "新建中..." }%>
  </div>
<% end %>

<script>
  // The date picker (read the docs)
  $('#ocean_inspect_date').pickadate({format: 'yyyy-mm-dd', max: true, formatSubmit: false})
  $('#ocean_inspect_s_time').pickatime({format: 'HH:i',formatSubmit: false})
  $('#ocean_inspect_e_time').pickatime({format: 'HH:i',formatSubmit: false})
</script>

app/views/ocean_inspects/show.html.erb
<% id = @ocean_inspect.year+@ocean_inspect.month+@ocean_inspect.day %>
<p></p>
<div class="col-md-10 offset-md-1 p-a-0">
  <h2 class="text-xs-center">澎湖南方四島國家公園海洋巡護紀錄表</h2>
  <hr>
  <div class="col-lg-6 col-xl-3 p-a-0" id="time">
    <p><span class="font-weight-bold p-a-0">日期： </span> <%= @ocean_inspect.month %> 月 <%= @ocean_inspect.day %> 日  |  星期<%= @ocean_inspect.wday %></p>
    <p><span class="font-weight-bold p-a-0">進出港時間：</span> <%= @ocean_inspect.s_time %> - <%= @ocean_inspect.e_time %></p>
  </div>
  <div class="col-lg-6 col-xl-4 p-a-0" id="tide">
    <% #拆分潮汐
     tide = WeatherMonthly.find(id).tide.gsub!(/[\[\]\"]/, "").split(",")
    %>
    <p class="p-a-0"><span class="font-weight-bold">潮汐時間：</span>&nbsp;&nbsp;<%= tide[0] %>&nbsp; | &nbsp;<%= tide[1] %></p>
    <p class="p-a-0"><span class="font-weight-bold"> &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;</span><%= tide[2] %> &nbsp;| &nbsp;<%= tide[3] %></p>
  </div>
  <div class="col-lg-12 col-xl-4 p-a-0" id="weather">
    <div class="section-1 col-lg-6 p-a-0">
      <p><span class="font-weight-bold p-a-0">天氣：</span> <%= WeatherMonthly.find(id).weather %></p>
      <p><span class="font-weight-bold p-a-0">風力：</span> <%= WeatherMonthly.find(id).wdlv %> 級</p>
    </div>
    <div class="section2 col-lg-6 p-a-0">
      <p><span class="font-weight-bold p-a-0">風向：</span> <%= WeatherMonthly.find(id).wdir %> </p>
      <p><span class="font-weight-bold p-a-0">浪高：</span> <%= WeatherMonthly.find(id).wave %> 米</p>
    </div>
  </div>
  <div class="col-lg-12 p-a-0" id="location">
    <hr>
    <p class="font-weight-bold p-a-0">巡查地點：</p>
    <p><%= @ocean_inspect.location %></p>
  </div>
  <div class="col-lg-12 col-xl-4 p-a-0" id="oil">
    <hr>
    <p class="col-lg-6 col-xl-12 p-a-0"><span class="font-weight-bold">航程： </span><%= @ocean_inspect.distance %> 浬 &nbsp;/ &nbsp;<span class="font-weight-bold">油耗：</span> <%= @ocean_inspect.gas_consumption %> 公升</p>
    <p class="col-lg-6 col-xl-12 p-a-0"><span class="font-weight-bold">加油： </span><%= @ocean_inspect.gas %> <%= "公升" if !@ocean_inspect.gas.nil? %></p>
  </div>
  <div class="col-lg-12 col-xl-8 p-a-0" id="work">
    <hr>
    <p class="font-weight-bold">執行項目：</p>
    <p><%= @ocean_inspect.work_items %></p>
  </div>
  <div class="col-lg-12 p-a-0" id="diary">
    <hr>
    <p class="font-weight-bold p-a-0">巡查紀事：</p>
      <ol>
        <% @ocean_inspect.diaries.each do |diary|%>
          <li><%= diary.item %></li>
        <% end %>
      </ol>
  </div>
  <div class="col-lg-12 p-a-0" id="pic">
    <hr>
    <p class="font-weight-bold p-a-0">巡查路線</p>
    <%= image_tag @ocean_inspect.map, class: "img-fluid m-x-auto ",style: "max-height: 400px;" %>
    <hr>
    <% if @ocean_inspect.pics? %>
      <p class="font-weight-bold p-a-0">巡查照片</p>
      <%= image_tag @ocean_inspect.pics, class: "img-fluid m-x-auto",style: "max-height: 400px;" %>
      <hr>
    <% end %>
  </div>
  <div class="col-lg-12 p-a-0" id="onboat">
    <p class="font-weight-bold">巡查人員：</p>
    <p><%= Staff.find(@ocean_inspect.leader).name %> 、 <%= @ocean_inspect.crew %></p>
  </div>
  <div class="col-lg-12 p-a-0" id="boat">
    <hr>
    <p class="col-lg-6 p-x-0"><span class="font-weight-bold">船長：</span> <%= Staff.find(@ocean_inspect.captain).name %></p>
    <p class="col-lg-6 p-x-0"><span class="font-weight-bold">使用船艇：</span> <%=  Boat.find(@ocean_inspect.boat_id).name%></p>
  </div>
  <div id="controll" class="col-lg-12 p-a-0 btn-group" role="group">
    <hr>
    <div class="col-md-3">
      <%= link_to("回報表清單", ocean_inspects_path, class: "btn btn-outline-success") %>
    </div>
    <div class="text-xs-right col-md-9" >
      <%= link_to("編輯紀錄表", edit_ocean_inspect_path(params[:id]), class: "btn btn-outline-danger") %>
      <!-- 多選button 輸出各種不同表單 -->
      <div class="btn-group  dropup">
        <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          輸出PDF表單
        </button>
        <div class="dropdown-menu">
          <%= link_to "巡護紀錄表", ocean_inspect_path(params[:id],format: "pdf"), target: '_blank',class: "dropdown-item" %>
          <%= link_to '航行日誌', logbooks_path(params[:id], format: 'pdf'), target: '_blank', class: "dropdown-item" %>
        </div>
      </div>

    </div>
  </div>
  <p></p>