config/routes.rb
Rails.application.routes.draw do
  resources :mail_lists
  resources :transportations
  resources :usefuls
  resources :ocean_inspects
  resources :staffs
  resources :boats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:  'ocean_inspects#index'
  resources :weathers
  resources :managements
  get 'ocean_inspects/:id/logbooks', to: 'ocean_inspects#logbooks', as: 'logbooks'
  get 'cwb', to: 'weathers#cwb', as: 'cwb'
  get 'record', to: 'ocean_inspects#record', as: 'record'
  get 'transportations/:id/sendmail', to: 'transportations#mailer', as: 'email'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  validates :name, presence: true
  validates :fuelConsumption, presence: true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :ocean_inspect
end

app/models/mail_list.rb
class MailList < ApplicationRecord
end

app/models/ocean_inspect.rb
class OceanInspect < ApplicationRecord
  has_many :diaries, dependent: :destroy, inverse_of: :ocean_inspect
  accepts_nested_attributes_for :diaries, reject_if: :all_blank, allow_destroy: true

  before_save do
    wday_i = self.date.to_date.wday.to_i
    @wday = "日" if wday_i === 0
    @wday = "一" if wday_i === 1
    @wday = "二" if wday_i === 2
    @wday = "三" if wday_i === 3
    @wday = "四" if wday_i === 4
    @wday = "五" if wday_i === 5
    @wday = "六" if wday_i === 6
    self.wday = @wday

    self.gas_consumption = self.distance.to_f * Boat.find(self.boat_id).fuelConsumption.to_f

    if attribute_present?("crew")
      self.crew.gsub!(/[\[\]\"]/, "")
      self.crew[0] = ""
      self.crew.gsub!(/,/, " 、")
    end
    if attribute_present?("location")
      self.location.gsub!(/[\[\]\"]/, "")
      self.location[0] = ""
      self.location.gsub!(/,/, " 、")
    end
    if attribute_present?("work_items")
      self.work_items.gsub!(/[\[\]\"]/, "")
      self.work_items[0] = ""
      self.work_items.gsub!(/,/, " 、")
    end
    @date = self.date
    self.year = @date.split("-")[0].to_i-1911
    self.month = @date.split("-")[1]
    self.day = @date.split("-")[2]

  end


  mount_uploader :pics, ImageUploader
  mount_uploader :map, ImageUploader

  # Validation
  validates :date, presence: true
  validates :s_time, presence: true
  validates :e_time, presence: true
  validates :boat_id, presence: true
  validates :captain, presence: true
  validates :distance, presence: true
  validates :leader, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :transportation_crews
  validates :name, presence: true
  validates :role, presence: true
end

app/models/transportation.rb
class Transportation < ApplicationRecord
  has_many :transportationcrews, dependent: :destroy, inverse_of: :transportation

  accepts_nested_attributes_for :transportationcrews, reject_if: :all_blank, allow_destroy: true

  before_save do
    @date = self.date
    self.year = @date.split("-")[0].to_i-1911
    self.month = @date.split("-")[1]
    self.day = @date.split("-")[2]
  end

  after_initialize :set_defaults, unless: :persisted?
  # The set_defaults will only work if the object is new

  def set_defaults
    self.note  ||= '搭乘內太空號運補船'
    self.concat ||= "(06) 999-1112"
  end

end

app/models/transportationcrew.rb
class Transportationcrew < ApplicationRecord
  belongs_to :transportation
end

app/models/useful.rb
class Useful < ApplicationRecord
  validates :name, presence: true
  validates :catalog, presence: true
end

app/models/weather_daily.rb
class WeatherDaily < ApplicationRecord
  belongs_to :weather_monthly
end

app/models/weather_monthly.rb
class WeatherMonthly < ApplicationRecord
  has_many :weather_dailies, dependent: :destroy

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: '船隻資料已新增' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: '船隻資料已更新' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.fetch(:boat, {})
      params.require(:boat).permit(:name, :fuelConsumption, :fuel_now)
    end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]


  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end




  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: '人員名單已新增' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: '人員名單已更新' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :title, :role, :phone, :email, :id_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/mail_lists_helper.rb
module MailListsHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/ocean_inspects_helper.rb
module OceanInspectsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/usefuls_helper.rb
module UsefulsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer" style="margin-top: 100px; padding: 20px;">
  <div class="col-xs-12"></div>
    <p class="text-xs-center text-muted m-b-0" style="font-size: 14px">Copyright ©2016 東吉管理站<br>-數位化業務系統3.0.1版-</p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!-- navbar -->
<header class="navbar navbar-dark navbar-full navbar-fixed-top bg-primary">
  <div class="container">
    <nav>
      <div class="clearfix">
        <button class="navbar-toggler hidden-md-up btn-primary btn-lg pull-xs-right" type="button" data-toggle="collapse" data-target="#nav_menu" aria-controls="nav_menu" aria-expanded="false" aria-label="Toggle navigation">
        &#9776;
        </button>
        <div><%= link_to "東吉管理站" , root_path , class: "navbar-brand h1 hidden-md-up" %></div>
      </div>
      <div id="nav_menu" class="collapse navbar-toggleable-sm" >
        <div class="nav navbar-nav" >
          <div><%= link_to "東吉管理站" , root_path , class: "navbar-brand h1 hidden-xs-down" %></div>
          <%= link_to '海域巡查', ocean_inspects_path,class: "nav-item nav-link active" %>
          <%= link_to '運補名冊', transportations_path,class: "nav-item nav-link active" %>
          <%= link_to '氣象資料', weathers_path,class: "nav-item nav-link active" %>
          <%= link_to '後台管理', managements_path,class: "nav-item nav-link active" %>
          <%= link_to '更新日誌', "https://github.com/hoshengwei/donji/commits/master",class: "nav-item nav-link active",target: '_blank' %>
          <a class="nav-item nav-link pull-sm-right" href="#">登入</a>
          <a class="nav-item nav-link pull-sm-right" href="#">註冊</a>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-TW">
  <head>
    <title>東吉管理站-數位化業務 Version 3.0.1</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tinymce_assets %>

  </head>

  <body>
  <%= render "/layouts/navbar" %>
  <div class="container">
    <div class="row">

    <!-- alert -->
    <% if notice != nil %>
      <div class="alert alert-success alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert != nil %>
      <div class="alert alert-warning alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= alert %>
      </div>
    <% end %>


    <!-- content area -->
    <%= yield %>

    </div>
  </div>
  <%= render "/layouts/footer" %>
  </body>
</html>