config/routes.rb
Rails.application.routes.draw do
  resources :mail_lists
  resources :transportations
  resources :usefuls
  resources :ocean_inspects
  resources :staffs
  resources :boats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:  'ocean_inspects#index'
  resources :weathers
  resources :managements
  get 'ocean_inspects/:id/logbooks', to: 'ocean_inspects#logbooks', as: 'logbooks'
  get 'cwb', to: 'weathers#cwb', as: 'cwb'
  get 'record', to: 'ocean_inspects#record', as: 'record'
  get 'transportations/:id/sendmail', to: 'transportations#mailer', as: 'email'
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController


  def index
    @boats = Boat.all
    @staffs = Staff.all
    @usefuls = Useful.all
    @staff = Staff.new
    @boat = Boat.new
    @useful = Useful.new
  end


  # # GET /boats/1
  # # GET /boats/1.json
  # def show
  # end
  #
  # # GET /boats/new
  # def new
  #   @boat = Boat.new
  # end
  #
  # # GET /boats/1/edit
  # def edit
  # end
  #
  # # POST /boats
  # # POST /boats.json
  # def create
  #   @boat = Boat.new(boat_params)
  #
  #   respond_to do |format|
  #     if @boat.save
  #       format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
  #       format.json { render :show, status: :created, location: @boat }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @boat.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /boats/1
  # # PATCH/PUT /boats/1.json
  # def update
  #   respond_to do |format|
  #     if @boat.update(boat_params)
  #       format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @boat }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @boat.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /boats/1
  # # DELETE /boats/1.json
  # def destroy
  #   @boat.destroy
  #   respond_to do |format|
  #     format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

private
  # Use callbacks to share common setup or constraints between actions.


end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/views/managements/_formboat.html.erb
<div class="modal-body">
  <%= simple_form_for(@boat) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name, label: "船隻名稱：", placeholder: "梅莉號" %>
      <%= f.input :fuelConsumption, label: "油耗(升/浬)：", placeholder: "100" %>
      <div class="modal-footer">
        <%= f.button :submit,"儲存資料",class: "btn btn-primary pull-xs-right" %>
        <%= link_to "返回後台", managements_path, class: "btn btn-secondary pull-xs-right",type: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/managements/_formstaff.html.erb
<div class="modal-body">
  <%= simple_form_for(@staff) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name, label: "姓名：", placeholder: "兩津勘吉" %>
      <%= f.input :title, label: "職稱", placeholder: "大猩猩" %>
      <%= f.input :role, collection: [:海洋國家公園, :警察小隊, :船公司, :其他] ,label: "所屬單位",placeholder: "偵探事務所",input_html: { class: "custom-select"}%>
      <%= f.input :id_number, label: "身份證字號", placeholder: "A123456789" %>
      <%= f.input :phone , label: "聯絡電話",placeholder: "0987-654-321"%>
      <%= f.input :email, label: "電子信箱", placeholder: "example@example.com" %>
      <div class="modal-footer">
        <%= f.button :submit,"儲存資料",class: "btn btn-primary pull-xs-right" %>
        <%= link_to "返回後台", managements_path, class: "btn btn-secondary pull-xs-right",type: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/managements/_formuseful.html.erb
<div class="modal-body">
  <%= simple_form_for(@useful) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name, label: "常用詞彙：", placeholder: "執行巡護勤務" %>
    <%= f.input :catalog, collection: [:工作項目,:巡查海域] ,label: "類別",input_html: { class: "custom-select"}%>
      <div class="modal-footer">
        <%= f.button :submit,"儲存資料",class: "btn btn-primary pull-xs-right" %>
        <%= link_to "返回後台", managements_path, class: "btn btn-secondary pull-xs-right",type: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/managements/index.html.erb
<!-- content -->
<div class="page-header">
  <p></p>
  <h2 class="h3">後台資料管理</h2>
  <hr>
</div>
<div class="content">
  <div id="staffs" class="col-xs-12 col-sm-6 col-lg-4">
    <div class="card">
      <img class="card-img-top img-fluid" src="/imgs/staffs.jpg" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">人員管理</h4>
        <h6 class="card-subtitle text-muted">工作人員名冊分類管理</h6>
        <hr>
        <p class="card-text">紀錄所有工作人員資訊以及所屬部門，供查閱資料與動態表單使用。</p>
      </div>
      <div class="list-group list-group-flush">
        <% @staffs.each do |staff| %>
          <%= link_to "#{staff.name}<span class=' pull-xs-right font-weight-normal text-muted'>#{staff.role}</span>".html_safe, staff_path(staff) ,class: "list-group-item list-group-item-action font-weight-bold"%>
        <% end %>
      </div>
      <div class="card-block">
        <button type="button" class="btn btn-primary card-link pull-xs-right" data-toggle="modal" data-target="#ModalStaff">
          新增人員名單
        </button>
      </div>
    </div>
  </div>
  <div id="boats" class="col-xs-12 col-sm-6 col-lg-4">
    <div class="card">
      <img class="card-img-top img-fluid" src="/imgs/boats.jpg" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">船隻管理</h4>
        <h6 class="card-subtitle text-muted">管理船隻相關資訊</h6>
        <hr>
        <p class="card-text">紀錄所有船隻相關資訊，方便進行船隻管理紀錄與油料推算管理。</p>
      </div>
      <div class="list-group list-group-flush">
        <% @boats.each do |boat| %>
          <%= link_to "#{boat.name}<span class=' pull-xs-right font-weight-normal text-muted'>油耗： #{boat.fuelConsumption} 升/浬</span>".html_safe, boat_path(boat) ,class: "list-group-item list-group-item-action font-weight-bold"%>
        <% end %>
      </div>
      <div class="card-block">
        <button type="button" class="btn btn-primary card-link pull-xs-right" data-toggle="modal" data-target="#ModalBoat">
          新增船隻清冊
        </button>
      </div>
    </div>
  </div>
  <div id="staffs" class="col-xs-12 col-sm-6 col-lg-4">
    <div class="card">
      <img class="card-img-top img-fluid" src="/imgs/usefuls.jpg" alt="Card image cap">
      <div class="card-block">
        <h4 class="card-title">常用詞彙</h4>
        <h6 class="card-subtitle text-muted">定型化文字分類管理</h6>
        <hr>
        <p class="card-text">設定常用文字，如巡查海域、工作項目等，避免重複輸入之麻煩。</p>
      </div>
      <div class="list-group list-group-flush">
        <% @usefuls.each do |useful| %>
          <%= link_to "#{useful.name}<span class=' pull-xs-right font-weight-normal text-muted'>#{useful.catalog}</span>".html_safe, useful_path(useful) ,class: "list-group-item list-group-item-action font-weight-bold"%>
        <% end %>
      </div>
      <div class="card-block">
        <button type="button" class="btn btn-primary card-link pull-xs-right" data-toggle="modal" data-target="#ModalUseful">
          新增常用詞彙
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Modal Staffs-->
<div class="modal fade" id="ModalStaff" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="ModalStaffLabel">新增人員名單</h4>
      </div>
      <%= render 'formstaff', staff: @staff %>
      </div>
    </div>
  </div>
</div>

<!-- Modal Boats-->
<div class="modal fade" id="ModalBoat" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="ModalStaffLabel">新增船隻清冊</h4>
      </div>
      <%= render 'formboat', boat: @boat %>
      </div>
    </div>
  </div>
</div>

<!-- Modal Boats-->
<div class="modal fade" id="ModalUseful" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="ModalStaffLabel">新增常用詞彙</h4>
      </div>
      <%= render 'formuseful', useful: @useful %>
      </div>
    </div>
  </div>
</div>